### ISSUE TITLE
Your SceneKit article isn't about SceneKit

### ISSUE THREAD

**Issue by JetForMe** [munirwanis/munirwanis.github.io#1]
Hey there. Thanks for the blog posts! I just wanted to let you know that your SceneKit [post](https://munirwanis.github.io/blog/2020/wwdc20-scenekit-swiftui/) is about SpriteKit, not SceneKit.

**Comment by munirwanis** [comment]
Hi Rick, thank you so much for the feedback! I may have confused framework names on the title. 😅
It's [fixed](https://munirwanis.github.io/blog/2020/wwdc20-spritekit-swiftui/) now! 😀

**Comment by JetForMe** [comment]
Cheers!

Feel free to do one on SceneKit and SwiftUI :)
